# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-23 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hPlay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1000)),
                ('last_name', models.CharField(blank=True, max_length=1000)),
                ('image', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='cover_art',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hPlay.Artist'),
        ),
    ]
