# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-23 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hPlay', '0002_auto_20161023_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
