# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-23 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hPlay', '0006_song_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Movie', 'Movie'), ('Pop', 'Pop'), ('Rock', 'Rock'), ('Alternative/Indie', 'Alternative/Indie'), ('Remix', 'Remix'), ('Instrumental', 'Instrumental'), ('Folk', 'Folk'), ('Electronic', 'Electronic')], default='Unknown', max_length=50),
        ),
    ]
